export type WorkerFnName = 'getMouse' 
| 'buildTower'
| 'saleTower' 
| 'handleSkill'

export type VueFnName = 'onWorkerReady'
| 'handlerTower' 
| 'showTowerBuilding' 
| 'buildTowerCallback'
| 'saleTowerCallback'
| 'unifiedMoney'
| 'onLevelChange'
| 'onHpChange'
| 'createAudio'
| 'onProgress'
| 'playDomAudio'