export type WorkerFnName = 'getMouse' 
| 'buildTower'
| 'saleTower' 

export type VueFnName = 'onWorkerReady'
| 'handlerTower' 
| 'showTowerBuilding' 
| 'buildTowerCallback'
| 'saleTowerCallback'
| 'changeMoney'
| 'onLevelChange'